language: node_js
node_js:
  - "8"

os: [linux]
dist: trusty
sudo: required

install:
  - npm run bootstrap

script:
  - npm test

before_deploy:
  - scripts/build-site.sh

deploy:
  provider: pages
  local-dir: www/public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
